Add support for PGID and PUID

diff --git a/Dockerfile.alpine b/Dockerfile.alpine
--- a/Dockerfile.alpine
+++ b/Dockerfile.alpine
@@ -1,5 +1,9 @@
 FROM python:3.11-alpine
 
+ENV PUID=1000
+ENV PGID=1000
+ENV GOSU_VERSION 1.17
+
 ENV DRYRUN 'True'
 ENV DEBUG 'True'
 ENV DEBUG_LEVEL 'INFO'
@@ -33,21 +37,45 @@ ENV BLACKLIST_USERS  ''
 ENV WHITELIST_USERS  ''
 
 
-RUN apk add --no-cache tini && \
-    addgroup --system jellyplex_user && \
-    adduser --system --no-create-home jellyplex_user --ingroup jellyplex_user && \
-    mkdir -p /app && \
-    chown -R jellyplex_user:jellyplex_user /app
+RUN apk add --no-cache tini
+
+# Install gosu
+RUN set -eux; \
+	\
+	apk add --no-cache --virtual .gosu-deps \
+		ca-certificates \
+		dpkg \
+		gnupg \
+	; \
+	\
+	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+	\
+# verify the signature
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+	gpgconf --kill all; \
+	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+	\
+# clean up fetch dependencies
+	apk del --no-network .gosu-deps; \
+	\
+	chmod +x /usr/local/bin/gosu; \
+# verify that the binary works
+	gosu --version; \
+	gosu nobody true
 
 WORKDIR /app
 
-COPY --chown=jellyplex_user:jellyplex_user ./requirements.txt ./
+COPY ./requirements.txt ./
 
 RUN pip install --no-cache-dir -r requirements.txt
 
-COPY --chown=jellyplex_user:jellyplex_user . .
+COPY . .
 
-USER jellyplex_user
+RUN chmod +x *.sh
 
-ENTRYPOINT ["/sbin/tini", "--"]
+ENTRYPOINT ["tini", "--", "/app/entrypoint.sh"]
 CMD ["python", "-u", "main.py"]
